### ISSUE TITLE
是否支持自定义过滤

### ISSUE THREAD

**Issue by swtseaman** [iamtsm/tl-ops-manage#6]
体验了下还不错； 想实现灰度； 用get请求的https://tlops.iamtsm.cn/?iamtsm=online 和offline看到了效果；
请问这个要怎么配置支持请求体里的内容，比如我要监听如果post json里面的某一个字段来转发不同环境，或者监听请求体内只要包含某字符串就转发到指定环境呢

**Comment by iamtsm** [comment]
> 体验了下还不错； 想实现灰度； 用get请求的https://tlops.iamtsm.cn/?iamtsm=online 和offline看到了效果； 请问这个要怎么配置支持请求体里的内容，比如我要监听如果post json里面的某一个字段来转发不同环境，或者监听请求体内只要包含某字符串就转发到指定环境呢

目前是只写了支持 url，cookie，args，header这几种，可以在管理后台看到。post内容体暂时还写，这个功能有空我补充下，如果是自行开发，可以参考以上几种的实现补充即可。
